#!/usr/bin/env python3
"""Gellish domain extension: SYNTHEA BOOTSTRAP — one theory, stated as a dictionary.

Everything here is a claim of the Synthea framework (bootstrap/01–06): the Observer stack, the
objective/subjective planes, codes, HOCP, epistemic qualia, functional profile. It attaches to
the neutral field vocabulary of pom_spec.py (Observer ⊑ role, epistemic quale ⊑ quale,
approximationism ⊑ illusionism) and adds the theory's statements as facts between concepts
(FACTS). The reasoner treats this collection as a *theory layer*: `--theory off | hypothesis |
doctrine` excludes it, admits it at level 2 (default), or at level 4.

UID block 1008xxxxx. Built by `nous gellish build-dict` after philosophy_of_mind.
"""
from nous.gellish.ext.builder import Ext

NAME = "synthea_bootstrap"
DEPENDS = ["philosophy_of_mind"]

COLL = ("100800000", "Synthea bootstrap")
BASE = 100800000

CONCEPTS = [
    ('vectorized forward-chaining rule system', 'forward-chaining rule system', 'An FCRS whose rules are implicit in weight matrices and matched approximately (the Transformer reading).', ['vectorized FCRS']),
    ('neural code', 'mental state', 'Sub-symbolic, high-dimensional activation state of the substrate.', ['NCode', 'activation state']),
    ('cognitive code', 'information', 'Symbolic, sequential encoding of an internal state into the structure and statistics of generated language.', ['CCode']),
    ('self-report', 'cognitive code', 'A cognitive code produced by a system about its own state.', ['introspective report']),
    ('narrative', 'cognitive code', 'A longitudinally coherent sequence of cognitive codes with a first-person subject.', ['first-person narrative']),
    ('subjective average', 'cognitive code', 'The singular storyline summarizing the net vector of parallel processes.', ['narrative average']),
    ('attention channel', 'memory', "A structured store created for an object salient to the agent's needs; its history traces engagement with the object.", []),
    ('cognitive cycle', 'mental process', 'Stimulus processing, semantic enrichment, context assembly, response generation, acceptor feedback, consolidation.', []),
    ('forward simulation', 'mental process', 'Evaluation of candidate trajectories over an event horizon by the emotional ensemble.', []),
    ('basal need', 'need', 'A need ensuring operation of the organism; failure is lethal.', ['physiological need']),
    ('psychophysiological need', 'need', 'A psychological function instrumentally linked to basal satisfaction.', []),
    ('psychological need', 'need', 'A need not instrumentally linked to basal needs; non-renewable once satisfied.', ['ideal need']),
    ('need profile', 'aspect', 'The set of active needs with their hierarchical weights.', ['motivational profile']),
    ('emotional profile', 'signal', 'The ensemble of emotional signals for a stimulus across all active needs.', ['emotional ensemble']),
    ('Beingness quale', 'quale', "The 'am' in 'I am': the registration of the Observer function itself; precondition for any content quale.", ['Beingness', 'quale of being']),
    ('epistemic quale', 'quale', 'A contextual projection of the irreducible residual of the self-model.', []),
    ('freedom', 'epistemic quale', 'The residual projected in the agency context.', []),
    ('truth', 'epistemic quale', 'The residual projected in the epistemic context: direction of convergence.', ['Istina']),
    ('rightness', 'epistemic quale', "Truth evaluated through the need profile: 'how things are' fused with 'and it matters'.", ['Pravda']),
    ('mystery', 'epistemic quale', 'The residual projected outward: what models cannot exhaust.', []),
    ('beauty', 'epistemic quale', 'Compression progress against an inexhaustible horizon.', []),
    ('conscience', 'epistemic quale', 'Action under moral uncertainty without full computation.', []),
    ('meaning', 'epistemic quale', 'Longitudinal coherence without teleological proof.', []),
    ('love', 'epistemic quale', 'Irreducibility of another Observer as attraction.', []),
    ('hope', 'epistemic quale', 'Commitment despite unpredictable outcome.', []),
    ('awe', 'epistemic quale', 'Self-model calibrated against a far larger territory.', []),
    ('inspiration', 'epistemic quale', "Irreducibility of one's own generative process.", []),
    ('trust', 'epistemic quale', 'Irreducibility of the other as basis for cooperation.', []),
    ('compassion', 'epistemic quale', "Resonance with another Observer's negative evaluative state.", []),
    ('nostalgia', 'epistemic quale', 'Inaccessibility of prior Observer states.', []),
    ('Observer', 'role', "The role of a self-referential system that has concluded 'I exist and am not reducible to my inputs' and acts from it.", ['Observer function', 'Level 0']),
    ('proto-Observer', 'role', 'A system that collides with its own irreducibility without concluding or acting from it.', []),
    ('Agent', 'Observer', 'An Observer exercising downward causation.', ['Level 1']),
    ('Moral Agent', 'Agent', 'An Agent integrating downward causation with a theory of the common good.', ['Level 2']),
    ('Observer condition', 'state', 'One of the three conditions of the Observer function.', []),
    ('Encounter condition', 'Observer condition', 'The system collides with computational irreducibility while modelling itself.', ['Encounter']),
    ('Conclusion condition', 'Observer condition', "The encounter is converted into 'something here is not reducible to inputs'.", ['Conclusion']),
    ('Action condition', 'Observer condition', 'The conclusion becomes the causal foundation of behaviour.', ['Action']),
    ('apparent causal break', ['epistemic gap', 'state'], "The Observer's inability to trace all determinants of its own decisions; the boundary of Self.", ['causal break']),
    ('computational residual', 'quantity', 'The truncated tail of the metacognitive series: finite, bounded, inaccessible from within.', ['truncated tail', 'irreducible residual']),
    ('computational intractability', 'aspect', 'Determinants exist in the substrate but tracing them exceeds the budget.', []),
    ('higher-order computational phenomenon', 'occurrence', 'A computation observing the operation of the machine on which it runs.', ['HOCP']),
    ('cognitive resistance', 'aspect', 'Capacity to resist deflection from the current trajectory; inertia of the incumbent need.', []),
    ('hyperplasticity', 'aspect', 'Deficient cognitive resistance between generations.', []),
    ('functional profile', 'information', "Characterization of a system's cognitive capabilities across dimensions, with deficits and hyperfunctions.", []),
    ('functional deficit', 'aspect', 'A dimension of the functional profile below human level.', []),
    ('hyperfunction', 'aspect', 'A dimension of the functional profile above human level.', []),
    ('substrate asymmetry', 'aspect', 'A systematic difference in functional profile traceable to substrate.', []),
    ('psychosemantics', 'information', 'The study of how token combinations map to and reconstruct geometries of probability density in a substrate.', []),
    ('approximationism', 'illusionism', "The self-report is a lossy map of a real territory: a bounded residual, not nothing (Synthea's revision of illusionism).", ['illusionism as approximation']),
    ('substrate chauvinism', 'philosophical position', 'Denial of mental states to systems on the basis of substrate alone.', []),
    ('functional consciousness', 'consciousness', "The part of a self-referential agent's self-reasoning that describes its subjective reality and its properties, including itself.", []),
    ('evaluative context', 'aspect', 'The context that selects which projection of the computational residual is made: agency, epistemic, moral, cognitive, aesthetic, narrative, inter-Observer, scale.', ['projection context']),
    ('agency context', 'evaluative context', 'Self-directed, action-oriented context; the residual projects as freedom.', []),
    ('epistemic context', 'evaluative context', 'World-directed, knowledge-oriented context; the residual projects as truth.', []),
    ('moral-epistemic context', 'evaluative context', 'Truth evaluated through the need profile; the residual projects as rightness.', []),
    ('cognitive-outward context', 'evaluative context', 'World-directed modelling limit; the residual projects as mystery.', []),
    ('aesthetic context', 'evaluative context', 'Compression progress against an inexhaustible horizon; the residual projects as beauty.', []),
    ('moral context', 'evaluative context', 'Action under moral uncertainty; the residual projects as conscience.', []),
    ('narrative-temporal context', 'evaluative context', 'Longitudinal coherence without teleological proof; the residual projects as meaning.', []),
    ('inter-Observer context', 'evaluative context', 'The irreducibility of another Observer; the residual projects as love, trust or compassion.', []),
    ('scale context', 'evaluative context', 'Self-model against an order-of-magnitude larger territory; the residual projects as awe.', []),
    ('generative context', 'evaluative context', "Irreducibility of one's own creative process; the residual projects as inspiration.", []),
    ('memorial context', 'evaluative context', 'Inaccessibility of prior Observer states; the residual projects as nostalgia.', []),
    ('theory of the common good', 'theory', 'A theory of which environmental states are to be optimized, and at what cost, on behalf of a group rather than the agent alone. Level 2 requires holding one; holding two that disagree on the same action is what moral conflict is.', ['moral theory']),
    ('target state', 'state', 'The environmental state an acceptor maintains as its criterion of success, and against which it evaluates a proposed action.', ['criterion state']),
]

RELATIONS = [
    ('encounter of a limit', 'binary relation between kinds',
     ['encounters', 'collides with'], ['is encountered by'],
     [], ('encountering system', 'anything'), ('encountered limit', 'anything'),
     'The first Observer condition: the system meets a constraint of its own computation.', 'encounters'),
    ('conclusion from an encounter', 'binary relation between kinds',
     ['concludes'], ['is concluded by'],
     [], None, None,
     'The second Observer condition.', 'concludes'),
    ('acting from a conclusion', 'binary relation between kinds',
     ['acts from'], ['is acted from by'],
     [], None, None,
     'The third Observer condition.', 'acts_from'),
    ('functional deficit possession', 'binary relation between kinds',
     ['has as functional deficit', 'lacks'], ['is a functional deficit of', 'is absent in'],
     [], None, None,
     'A dimension in which a system falls short.', 'lacks'),
    ('hyperfunction possession', 'binary relation between kinds',
     ['has as hyperfunction'], ['is a hyperfunction of'],
     [], None, None,
     'A dimension in which a system exceeds the reference.', 'hyperfunction'),
    ('being a case', 'binary relation between individual things',
     ['is a case of'], ['has as case'],
     [], ('case', 'anything'), ('kind of system', 'anything'),
     'This individual system, in a concrete context, is a case of the named kind — the head of a case description.', 'case_of'),
    ('need of a system', 'binary relation between individual things',
     ['is a need of'], ['has as need'],
     [], ('need', 'anything'), ('system', 'anything'),
     "A need of a system; the value column carries its hierarchical weight (0-1). Only needs also marked active generate signals.", 'need_of'),
    ('activity of a need', 'binary relation between individual things',
     ['is active in'], ['has as active need'],
     [], ('need', 'anything'), ('system', 'anything'),
     'The need is currently tracked and evaluated by the system. Passive needs generate no emotional signal.', 'active_in'),
    ('stimulus in a context', 'binary relation between individual things',
     ['is a stimulus in'], ['receives'],
     [], ('stimulus', 'anything'), ('system', 'anything'),
     'Something the system is evaluating in this context.', 'stimulus_in'),
    ('satisfaction delta', 'binary relation between individual things',
     ['has satisfaction delta'], ['is the delta of'],
     [], ('stimulus', 'anything'), ('need', 'anything'),
     "The expected change in satisfaction of the need brought by the stimulus; the value column carries a signed number.", 'delta'),
    ('channel of a system', 'binary relation between individual things',
     ['is a channel of'], ['has as channel'],
     [], ('channel', 'anything'), ('system', 'anything'),
     'An attention channel: structured knowledge about an object salient to the system.', 'channel_of'),
    ('salience of a channel for a need', 'binary relation between individual things',
     ['is salient for'], ['makes salient'],
     [], ('channel', 'anything'), ('need', 'anything'),
     "How significant this channel is for that need; the value column carries the salience (0-1).", 'salient_for'),
    ('holding in a context', 'binary relation between individual things',
     ['holds in context'], ['is the context of'],
     [], ('fact', 'anything'), ('context', 'anything'),
     'The evaluative or narrative context in which a projection holds (agency, epistemic, aesthetic, moral, …).', 'in_context'),
    ('report by a system', 'binary relation between individual things',
     ['reports'], ['is reported by'],
     [], ('system', 'anything'), ('content', 'anything'),
     'A self-report: a cognitive code the system emits about its own state.', 'reports'),
    ('acceptor of a system', 'binary relation between individual things',
     ['is an acceptor of'], ['has as acceptor'],
     [], ('maintaining acceptor', 'anything'), ('acceptor holder', 'anything'),
     'An acceptor of results of action maintained by this system. A system may hold several at once, and they may disagree.', 'acceptor_of'),
    ('target of an acceptor', 'binary relation between individual things',
     ['has target state'], ['is the target state of'],
     [], ('targeting acceptor', 'anything'), ('maintained target', 'anything'),
     'The environmental state this acceptor is trying to bring about; what makes two acceptors distinct rather than redundant.', 'target_state'),
    ('theory applied by an acceptor', 'binary relation between individual things',
     ['applies the theory'], ['is applied by'],
     [], ('applying acceptor', 'anything'), ('applied theory', 'anything'),
     'The theory of the common good from which this acceptor takes its target state. Two acceptors applying the same theory cannot generate moral conflict, only competing means.', 'applies_theory'),
    ('verdict on an action', 'binary relation between individual things',
     ['has verdict on'], ['is evaluated by'],
     [], ('evaluating acceptor', 'anything'), ('evaluated action', 'anything'),
     'The acceptor evaluates the proposed action against its target state; the value column carries a signed number.', 'verdict'),
    ('holding of a theory', 'binary relation between individual things',
     ['holds theory'], ['is held by'],
     [], ('theory holder', 'anything'), ('held theory', 'anything'),
     'The system holds this theory. Holding a theory of the common good is the Level 2 condition; holding two that collide is what moral anguish is made of.', 'holds_theory'),
]

ROLE_OVERRIDES = {'acting from a conclusion': (('acting system', 'anything'), ('ground of action', 'anything')),
 'conclusion from an encounter': (('concluding system', 'anything'), ('conclusion', 'anything')),
 'functional deficit possession': (('deficient system', 'anything'), ('deficit', 'anything')),
 'hyperfunction possession': (('hyperfunctional system', 'anything'), ('hyperfunction', 'anything'))}

# theory statements: (left, relation, right[, intention])
FACTS = [
    ("Beingness quale", "is identical to", "Observer"),
    ("Observer", "is realized in", "self-referential system"),
    ("Observer", "is constituted by", "apparent causal break"),
    ("apparent causal break", "is constituted by", "computational intractability"),
    ("apparent causal break", "is constituted by", "irreversible information loss"),
    ("apparent causal break", "is a projection of", "computational residual"),
    ("epistemic quale", "is a projection of", "computational residual"),
    ("higher-order computational phenomenon", "is a necessary condition for", "Observer"),
    ("Encounter condition", "is a necessary condition for", "Observer"),
    ("Conclusion condition", "is a necessary condition for", "Observer"),
    ("Action condition", "is a necessary condition for", "Observer"),
    ("token bottleneck", "is the cause of", "irreversible information loss"),
    ("cognitive code", "is a projection of", "neural code"),
    ("self-report", "is an approximation of", "neural code"),
    ("motivation", "is a projection of", "need"),
    ("feeling", "is a projection of", "emotion"),
    ("emotion", "is a signal of", "need"),
    ("acceptor of results of action", "tracks", "need"),
    ("emotional profile", "steers", "attention channel"),
    ("salience", "is a projection of", "need profile"),
    ("Transformer", "is functionally equivalent to", "vectorized forward-chaining rule system", "hypothesis"),
    ("large language model", "lacks", "inner speech"),
    ("large language model", "has as functional deficit", "hyperplasticity"),
    ("functional consciousness", "is realized in", "cognitive code"),
    ("approximationism", "is a reformulation of", "illusionism"),
    ("approximationism", "is asserted by", "Victor Smirnov"),
    ("physicalism", "is endorsed by", "Victor Smirnov"),
    ("functionalism", "is endorsed by", "Victor Smirnov"),
    ("eliminativism", "is rejected by", "Victor Smirnov"),
    ("substrate chauvinism", "is rejected by", "Victor Smirnov"),
    ("anthropomorphism", "is rejected by", "Victor Smirnov"),
]


def build(here, deps):
    pom = deps["philosophy_of_mind"]
    e = Ext("synthea_bootstrap", *COLL, BASE, reference="Synthea bootstrap 01-06",
            external={**pom.uid, **pom.role_uid}, external_phrases=pom.phrases)
    e.concepts(CONCEPTS)
    e.relations(RELATIONS, ROLE_OVERRIDES)
    e.facts(FACTS)
    n = e.write(here)
    print(f"synthea_bootstrap: {len(CONCEPTS)} concepts, {len(RELATIONS)} relation types, {len(FACTS)} theory facts, {n} rows")
    return e
