#!/usr/bin/env python3
"""Gellish domain extension: PHILOSOPHY OF MIND — the field, position-neutral.

Positions, arguments, distinctions, neighbouring theories, people, and the relation types the
field uses (dialectical, provenance, projection/realization/supervenience...). No claims about
which position is right: `illusionism` is a position, not a fact; `consciousness` is the
explanandum, not Synthea's definition of it. Synthea's own theory lives in synthea_spec.py and
attaches to this vocabulary.

UID block 1007xxxxx. Built by `nous gellish build-dict`.
"""
from nous.gellish.ext.builder import Ext

NAME = "philosophy_of_mind"
DEPENDS = []

COLL = ("100700000", "Philosophy of mind (field)")
BASE = 100700000

# (name, supertype | [supertypes], definition, synonyms)
CONCEPTS = [
    ('cognitive system', 'system', 'A system that processes information to guide behaviour.', ['mind', 'cognitive agent']),
    ('self-referential system', 'cognitive system', 'A cognitive system whose model includes itself as an object.', ['self-applicable system']),
    ('substrate', 'physical object', 'The physical medium in which a cognitive function is realized.', ['computational substrate']),
    ('biological substrate', 'substrate', 'Neural tissue as a substrate of cognition.', ['wetware']),
    ('silicon substrate', 'substrate', 'Digital hardware as a substrate of cognition.', ['digital substrate', 'hardware substrate']),
    ('brain', ['biological substrate', 'cognitive system'], 'The organ realizing cognition in animals.', []),
    ('large language model', ['neural network', 'cognitive system'], 'An autoregressive neural network trained to predict text tokens.', ['LLM', 'language model']),
    ('Transformer', 'neural network', 'A neural network architecture built from attention blocks and feed-forward modules.', ['Transformer architecture', 'Transformer model']),
    ('forward-chaining rule system', 'cognitive system', 'A system whose behaviour is a cycle of pattern matching over working memory, conflict resolution and rule firing.', ['FCRS', 'production system', 'pattern matching system']),
    ('cognitive architecture', 'model', 'A specification of the components and cycle of a cognitive system.', []),
    ('self-model', 'model', "A system's representation of itself.", ['model of self']),
    ('world model', 'model', "A cognitive system's model of its environment.", ['model of environment']),
    ('mental state', 'state', 'A state of a mind or cognitive system.', ['cognitive state']),
    ('mental process', 'activity', 'An activity of a cognitive system operating on mental states.', ['cognitive process']),
    ('working memory', 'memory', 'The memory whose contents are directly available to the current cognitive cycle.', ['context window']),
    ('memory consolidation', 'mental process', 'Stabilisation and reorganisation of memory traces after encoding.', []),
    ('metacognition', 'mental process', "Computation of further terms of the self-model series: reflection on one's own states.", ['reflection']),
    ('introspection', 'metacognition', 'Metacognition directed at producing a self-report.', []),
    ('chain of thought', 'mental process', 'Externalization of intermediate reasoning steps into tokens.', ['CoT', 'reasoning trace']),
    ('inner speech', 'mental process', 'A continuous sub-symbolic carrier signal for self-directed language.', ['inner monologue']),
    ('need', 'aspect', 'A state of an organism or system that drives behaviour toward a goal.', ['drive']),
    ('acceptor of results of action', 'mechanism', 'Anokhin: a maintained anticipation of a result compared against afferent feedback.', ['acceptor', 'result acceptor']),
    ('emotion', 'signal', "An evaluative state or signal relating a stimulus to the organism's concerns.", []),
    ('valence', 'quality', 'Positive or negative sign of an affective state.', []),
    ('salience', 'quantity', 'The degree to which a stimulus attracts processing resources.', []),
    ('prediction error', 'signal', 'Difference between predicted and actual input (predictive processing).', []),
    ('motivational conflict', 'state', 'Co-active goals that cannot all be satisfied.', ['need conflict']),
    ('motivation', 'mental state', 'The disposition to pursue a goal.', []),
    ('feeling', 'mental state', 'The subjectively reported aspect of an affective state.', []),
    ('thought', 'mental state', 'A discrete, reportable content of reasoning.', []),
    ('intuition', 'mental state', 'A judgement reached without an articulable path.', []),
    ('consciousness', 'mental process', "The property of a system's having experience or awareness; the explanandum of the field.", ['awareness']),
    ('phenomenal consciousness', 'consciousness', 'Consciousness as what-it-is-likeness (Block).', ['P-consciousness']),
    ('access consciousness', 'consciousness', 'Consciousness as global availability of content for reasoning and report (Block).', ['A-consciousness']),
    ('quale', 'mental state', 'A content of experience individuated by its structural role.', ['qualia']),
    ('content quale', 'quale', 'A quale of a sensory or conceptual content (redness, sourness).', []),
    ('epistemic gap', 'aspect', 'A difference between a description and what it describes that the describer cannot close.', []),
    ('self-model gap', 'epistemic gap', "The difference between a system's self-model and the process it models (cf. Metzinger).", []),
    ('explanatory gap', 'epistemic gap', 'The gap between physical description and phenomenal character (Levine).', []),
    ('computational irreducibility', 'aspect', 'The property of a process that cannot be predicted faster than by running it (Wolfram).', []),
    ('irreversible information loss', 'occurrence', 'Destruction of information at a processing bottleneck.', []),
    ('token bottleneck', ['mechanism', 'occurrence'], 'In an autoregressive model, the collapse of the output distribution to one token per step.', ['softmax collapse']),
    ('downward causation', ['aspect', 'mental causation'], 'Causation from a higher level of organisation to its constituents; contested in philosophy of mind.', ['DC']),
    ('computational constraint', 'aspect', 'A finite resource of a machine: time, memory, bandwidth.', ['resource constraint']),
    ('intrapersonal intelligence', 'aspect', "Capacity to model and regulate one's own mental states (Gardner).", []),
    ('theory', 'information', 'A systematic body of claims with explanatory intent.', []),
    ('philosophical position', 'theory', 'A theory taking a stance on a philosophical question.', ['position', 'doctrine']),
    ('theory of mind', 'theory', 'A theory of the nature of mental states.', []),
    ('physicalism', 'philosophical position', 'All mental phenomena are products of physical processes.', ['materialism']),
    ('dualism', 'philosophical position', 'Mental and physical are distinct substances or properties.', []),
    ('functionalism', 'philosophical position', 'Mental states are individuated by causal role, not substrate.', []),
    ('computationalism', 'functionalism', 'Mental processes are computations.', []),
    ('illusionism', 'philosophical position', 'Phenomenal consciousness is an introspective misrepresentation (Frankish, Dennett).', []),
    ('eliminativism', 'philosophical position', 'Folk-psychological mental states do not exist.', []),
    ('panpsychism', 'philosophical position', 'Experience is a fundamental feature of matter.', []),
    ('identity theory', 'physicalism', 'Mental state types are identical to brain state types.', []),
    ('behaviourism', 'philosophical position', 'Mental terms refer to behavioural dispositions.', ['behaviorism']),
    ('higher-order theory', 'theory of mind', 'A state is conscious when it is the object of a higher-order representation.', ['HOT']),
    ('global workspace theory', 'theory of mind', 'Consciousness as global broadcast of content (Baars).', ['GWT']),
    ('integrated information theory', 'theory of mind', 'Consciousness as integrated information (Tononi).', ['IIT']),
    ('predictive processing', 'theory of mind', 'Cognition as hierarchical prediction-error minimization.', ['predictive coding']),
    ('somatic marker hypothesis', 'theory of mind', 'Low-level emotional signals are constitutive for decision-making (Damasio).', []),
    ('theory of functional systems', 'theory of mind', 'Behaviour organized around acceptors of results of action (Anokhin).', ['TFS']),
    ('anthropomorphism', 'philosophical position', 'Attribution of human-specific states to a non-human system.', ['anthropomorphic frame']),
    ('folk psychology', 'theory', 'The everyday vocabulary of beliefs, desires and feelings.', []),
    ('philosophical argument', 'information', 'A structured set of premises offered for a conclusion.', ['argument']),
    ('thought experiment', 'philosophical argument', 'An argument by imagined scenario.', []),
    ('psychophysical problem', 'question', 'The problem of how mental phenomena relate to physical processes; the family of questions a theory of mind must answer. Its components are the phenomena to be explained.', ['mind-body problem', 'mind–body problem']),
    ('phenomenal experience', 'mental state', 'Experience with a qualitative character; that there is something it is like.', ['subjective experience', 'conscious experience', 'what it is like', 'something it is like', 'phenomenal character']),
    ('unity of consciousness', 'aspect', 'The fact that experience presents as one subject at a time.', ['subjective unity', 'unity of the Subject', 'unity of the self', 'binding']),
    ('temporal unity of the self', 'aspect', 'The single experienced timeline and felt authorship of decisions in time.', ['timeline of the Subject', 'subjective timeline', 'timeline', 'timeline illusion']),
    ('free will', 'aspect', 'Felt openness of choice and authorship of action.', ['freedom of will', 'freedom of the will', 'felt freedom', 'freedom', 'agency']),
    ('mental causation', 'aspect', 'The causal efficacy of mental states in a physically closed world.', ['causal efficacy of mental states', 'exclusion problem']),
    ('other minds', 'question', 'Whether and how another system has experience, and what it is like for it.', ['problem of other minds', 'bat experience', 'other Observer']),
    ('the self', 'aspect', 'The subject of experience and its boundary from the environment.', ['self', 'Self', 'subject', 'Subject', 'I', 'boundary of Self', 'Self/Environment boundary', 'self/environment boundary']),
    ('hard problem of consciousness', 'question', 'Why physical processing is accompanied by experience at all (Chalmers).', ['hard problem']),
    ('bat question', ['question', 'other minds'], 'What it is like to be a bat (Nagel).', ["Nagel's bat question"]),
    ('zombie argument', 'thought experiment', 'Conceivability of a functional duplicate without experience.', []),
    ('Chinese room', 'thought experiment', 'Symbol manipulation without understanding (Searle).', []),
    ('knowledge argument', 'thought experiment', 'Mary the colour scientist (Jackson).', []),
    ('philosopher', 'person', 'A person who produces philosophical arguments.', []),
    ('neuroscientist', 'person', 'A scientist of the nervous system.', []),
    ('psychologist', 'person', 'A scientist of behaviour and mental processes.', []),
    ('physiologist', 'person', 'A scientist of the functioning of organisms.', []),
    ('computer scientist', 'person', 'A scientist of computation.', []),
    ('enactivism', 'philosophical position', 'Cognition as embodied action of an organism in its environment (Varela, Thompson, Rosch).', []),
    ('dual-process theory', 'theory of mind', 'Fast heuristic System 1 and slow deliberate System 2 as distinct subsystems (Kahneman).', ['System 1/System 2']),
    ('artificial curiosity', 'theory of mind', 'Interest as the first derivative of compression progress (Schmidhuber).', ['compression progress theory']),
    ('multiple drafts model', 'theory of mind', 'Consciousness as parallel content revisions with no central theatre (Dennett).', []),
    ('Rete algorithm', 'mechanism', 'Pattern-matching network caching partial matches for forward-chaining rule systems (Forgy).', ['Rete']),
    ('philosophical claim', 'proposition', 'A claim made within a philosophical argument or position.', ['thesis']),
    ('hypothesis', 'proposition', 'A claim offered as a conjecture to be tested.', ['conjecture']),
    ('prediction', 'proposition', 'A claim about what will be observed.', []),
    ('objection', 'proposition', 'A claim raised against another claim.', []),
    ('metaphor', 'information', 'A figurative expression of one thing in terms of another.', ['figure']),
    ('analogy', 'information', 'A structural similarity offered without identity.', []),
]

# (name, supertype, base phrases, inverse phrases, algebraic props, role1, role2, definition, sem tag)
RELATIONS = [
    ('projection of a state into a code', 'modeling of an object',
     ['is a projection of', 'is a low-dimensional projection of'], ['is projected as', 'projects to'],
     [], ('projection', 'anything'), ('projected state', 'anything'),
     'A code is a dimensionality-reducing image of a state.', None),
    ('approximation of a process', 'modeling of an object',
     ['is an approximation of', 'approximates'], ['is approximated by'],
     [], ('approximation', 'anything'), ('approximated process', 'anything'),
     'A lossy but faithful model of a process.', None),
    ('conceptualization', 'modeling of an object',
     ['is conceptualized as', 'is conceptualised as'], ['is a conceptualization of'],
     [], None, None,
     'A phenomenon is given a conceptual description.', None),
    ('experiential projection', 'projection of a state into a code',
     ['is experienced as', 'is felt as'], ['is the experience of'],
     [], None, None,
     "A state appears in the subject's narrative as a given feeling or quale.", None),
    ('manifestation', 'binary relation between kinds',
     ['manifests as', 'is manifested as'], ['is a manifestation of'],
     [], None, None,
     'A structure appears in a given context in a given form.', None),
    ('encoding', 'binary relation between kinds',
     ['encodes', 'is an encoding of'], ['is encoded in', 'is encoded as'],
     [], ('encoder', 'anything'), ('encoded content', 'anything'),
     'Information carries the structure of a state.', None),
    ('realization of a function in a substrate', 'binary relation between kinds',
     ['is realized in', 'is realised in', 'is implemented in', 'runs on'], ['realizes', 'realises', 'implements', 'is a substrate of'],
     [], ('realized function', 'anything'), ('realizing substrate', 'substrate'),
     'A cognitive function is physically instantiated by a substrate.', None),
    ('supervenience', 'binary relation between kinds',
     ['supervenes on'], ['is a supervenience base of', 'subvenes'],
     ['transitive relation', 'antisymmetric relation'], None, None,
     'No difference in the supervening without a difference in the base.', None),
    ('constitution', 'binary relation between kinds',
     ['is constituted by', 'is grounded in', 'is composed of', 'consists of', 'is made up of'], ['constitutes', 'grounds', 'makes up'],
     ['transitive relation'], ('constituted whole', 'anything'), ('constituent', 'anything'),
     'Non-causal making-up: the whole is nothing over and above the constituents. Not causation. Shadows Gellish 5623 for abstract wholes.', 'has_part'),
    ('reduction', 'binary relation between kinds',
     ['is reducible to', 'is reduced to', 'reduces to'], ['is a reduction base of'],
     ['transitive relation'], None, None,
     'The higher-level description is explicable in terms of the lower.', None),
    ('functional equivalence', 'binary relation between kinds',
     ['is functionally equivalent to'], ['is functionally equivalent to'],
     ['symmetric relation', 'transitive relation'], None, None,
     'Same causal input-output profile regardless of substrate.', None),
    ('functional analogy', 'binary relation between kinds',
     ['is a functional analogue of', 'is a functional analog of', 'is functionally analogous to'], ['is a functional analogue of'],
     ['symmetric relation'], None, None,
     'Corresponding causal role in different systems.', None),
    ('structural analogy', 'binary relation between kinds',
     ['is analogous to', 'is structurally analogous to', 'is an analogy for', 'parallels', 'resembles'], ['is analogous to'],
     ['symmetric relation'], None, None,
     'Structural similarity without identity.', 'analogous_to'),
    ('metaphorical expression', 'binary relation between kinds',
     ['is a metaphor for', 'is figuratively expressed as'], ['is expressed by the metaphor'],
     [], ('metaphor', 'anything'), ('figured object', 'anything'),
     'One thing is spoken of in terms of another; not identity, not classification.', None),
    ('signalling of need satisfaction', 'binary relation between kinds',
     ['is a signal of', 'signals'], ['is signalled by', 'is signaled by'],
     [], ('signal', 'anything'), ('signalled state', 'anything'),
     'An emotional signal carries the expected satisfaction of a need.', None),
    ('tracking', 'binary relation between kinds',
     ['tracks', 'is tracked against'], ['is tracked by'],
     [], ('tracker', 'anything'), ('tracked target', 'anything'),
     'An acceptor maintains a target and compares outcomes against it.', None),
    ('evaluation', 'binary relation between kinds',
     ['evaluates'], ['is evaluated by'],
     [], None, None,
     'Assigns a value relative to active needs.', None),
    ('influence', 'being influenced',
     ['influences', 'acts on'], ['is influenced by'],
     [], None, None,
     'General causal modulation.', None),
    ('steering of attention', 'influence',
     ['steers', 'directs'], ['is steered by'],
     [], None, None,
     'An evaluative signal biases where the system looks next.', None),
    ('modulation', 'influence',
     ['modulates'], ['is modulated by'],
     [], None, None,
     'Continuous adjustment of a process by a signal.', None),
    ('inhibition', 'influence',
     ['inhibits', 'suppresses'], ['is inhibited by', 'is suppressed by'],
     [], None, None,
     'Reduction of a process by another.', None),
    ('amplification', 'influence',
     ['amplifies'], ['is amplified by'],
     [], None, None,
     'Increase of a process by another.', None),
    ('gating', 'influence',
     ['gates'], ['is gated by'],
     [], None, None,
     'Admission of a process is conditional on another.', None),
    ('optimization', 'binary relation between kinds',
     ['maximizes', 'optimizes', 'optimises'], ['is maximized by'],
     [], None, None,
     'A process moves a quantity toward its extremum.', None),
    ('minimization', 'optimization',
     ['minimizes', 'minimises'], ['is minimized by'],
     [], None, None,
     'Optimization toward a minimum.', None),
    ('monitoring', 'binary relation between kinds',
     ['monitors', 'observes'], ['is monitored by', 'is observed by'],
     [], ('monitor', 'anything'), ('monitored object', 'anything'),
     'A computation observes a process or the machine it runs on.', None),
    ('directedness', 'binary relation between kinds',
     ['is directed toward', 'is directed towards', 'is directed at', 'is about'], ['is the object of'],
     [], ('directed state', 'anything'), ('intentional object', 'anything'),
     'Intentionality: aboutness of a mental state.', None),
    ('persistence across', 'binary relation between kinds',
     ['persists across'], ['is spanned by'],
     [], None, None,
     'A structure survives a sequence of steps.', None),
    ('generation', 'binary relation between kinds',
     ['generates', 'produces', 'gives rise to'], ['is generated by', 'arises from'],
     [], None, None,
     'A process brings a structure into existence.', None),
    ('reconstruction', 'binary relation between kinds',
     ['reconstructs'], ['is reconstructed by', 'is reconstructed from'],
     [], None, None,
     'A receiver rebuilds a state from a code.', None),
    ('functional role possession', 'binary relation between kinds',
     ['has as functional role', 'has functional role', 'plays the functional role of'], ['is a functional role of'],
     [], None, None,
     "A component's causal role in a system.", None),
    ('exhibition of a property', 'possession of a property',
     ['exhibits', 'displays', 'shows'], ['is exhibited by'],
     [], None, None,
     'Observable manifestation of a property.', None),
    ('explanation', 'binary relation between individual things',
     ['explains', 'accounts for'], ['is explained by', 'is accounted for by'],
     [], ('explanans', 'anything'), ('explanandum', 'anything'),
     'A theory or claim makes a phenomenon intelligible.', None),
    ('prediction relation', 'binary relation between individual things',
     ['predicts'], ['is predicted by'],
     [], None, None,
     'A theory entails an observation.', None),
    ('evidential support', 'binary relation between individual things',
     ['is evidence for', 'supports'], ['is supported by', 'is evidenced by'],
     [], None, None,
     'An observation raises the credibility of a claim.', 'elaborated_by_inv'),
    ('elaboration', 'binary relation between individual things',
     ['is elaborated by', 'is illustrated by', 'is exemplified by'], ['elaborates', 'illustrates', 'exemplifies'],
     [], None, None,
     'A claim is developed or illustrated by another.', 'elaborated_by'),
    ('necessary condition', 'binary relation between individual things',
     ['is a necessary condition for', 'is a necessary condition of', 'is necessary for', 'is required for', 'is a prerequisite for', 'is a precondition for', 'is presupposed by'], ['requires', 'presupposes', 'depends on', 'has as necessary condition'],
     ['transitive relation'], None, None,
     'B cannot hold unless A holds: B implies A.', 'necessary_for'),
    ('sufficient condition', 'binary relation between individual things',
     ['is a sufficient condition for', 'is a sufficient condition of', 'is sufficient for', 'guarantees'], ['has as sufficient condition'],
     ['transitive relation'], None, None,
     'A holding is enough for B: A implies B.', 'sufficient_for'),
    ('logical equivalence', 'binary relation between individual things',
     ['is logically equivalent to', 'is equivalent to', 'is a biconditional of'], ['is logically equivalent to'],
     ['symmetric relation', 'transitive relation'], None, None,
     'Mutual implication.', 'equivalent_to'),
    ('identity', 'binary relation between kinds',
     ['is identical to', 'is the same as', 'is identified with', 'is synonymous with'], ['is identical to'],
     ['symmetric relation', 'transitive relation'], None, None,
     'One thing under two descriptions.', 'identical_to'),
    ('distinctness', 'binary relation between kinds',
     ['is distinct from', 'differs from', 'is not identical to', 'is not the same as'], ['is distinct from'],
     ['symmetric relation'], None, None,
     'Two things, not one.', 'not_equal_to'),
    ('negative classification', 'binary relation between individual things',
     ['is not classified as a', 'is not classified as', 'is not classified as an', 'is not an instance of', 'is not a', 'is not an'], ['does not classify'],
     [], None, None,
     'Explicit denial of classification.', 'not_classified_as'),
    ('contrast', 'binary relation between individual things',
     ['contrasts with', 'is contrasted with', 'is opposed to', 'stands in contrast to', 'is in tension with'], ['contrasts with'],
     ['symmetric relation'], None, None,
     'Two claims are set against each other.', 'contrasts_with'),
    ('objection', 'binary relation between individual things',
     ['is an objection to', 'is a critique of', 'is raised against', 'challenges'], ['is challenged by', 'has as objection'],
     [], None, None,
     'A claim is raised against another.', None),
    ('rebuttal', 'objection',
     ['is raised to rebut', 'rebuts', 'is a rebuttal of', 'refutes'], ['is rebutted by', 'is refuted by'],
     [], None, None,
     'A claim is raised in order to reject another.', 'raised_to_rebut'),
    ('reply', 'binary relation between individual things',
     ['is a reply to', 'answers', 'responds to'], ['is answered by'],
     [], None, None,
     'A claim addresses an objection.', None),
    ('concession', 'binary relation between individual things',
     ['is conceded by'], ['concedes'],
     [], None, None,
     "'Although A, nevertheless B'.", 'conceded_by'),
    ('counterexample', 'binary relation between individual things',
     ['is a counterexample to'], ['has as counterexample'],
     [], None, None,
     'A case that falsifies a general claim.', 'counterexample_to'),
    ('inversion of a question', 'binary relation between individual things',
     ['is an inversion of', 'inverts'], ['is inverted by'],
     [], None, None,
     'A question or claim with the roles of its terms exchanged.', None),
    ('generalization', 'binary relation between individual things',
     ['generalizes', 'generalises', 'is a generalization of'], ['is a special case of'],
     ['transitive relation'], None, None,
     'A claim covers another as an instance.', None),
    ('reformulation', 'binary relation between individual things',
     ['is a reformulation of', 'restates'], ['is reformulated as'],
     [], None, None,
     'Same content, different expression.', None),
    ('assertion by a party', 'binary relation between individual things',
     ['is asserted by', 'is claimed by', 'is proposed by', 'is argued by', 'is stated by', 'is held by', 'is posed by'], ['asserts', 'claims', 'proposes', 'argues', 'holds', 'poses'],
     [], ('asserted claim', 'anything'), ('asserting party', 'anything'),
     'Provenance of a claim.', 'asserted_by'),
    ('endorsement', 'binary relation between individual things',
     ['is endorsed by', 'is accepted by', 'is adopted by', 'is affirmed by'], ['endorses', 'accepts', 'adopts'],
     [], ('endorsed claim', 'anything'), ('endorsing party', 'anything'),
     "A party's positive stance toward a claim.", 'endorsed_by'),
    ('rejection', 'binary relation between individual things',
     ['is rejected by', 'is denied by', 'is disputed by'], ['rejects', 'denies', 'disputes'],
     [], ('rejected claim', 'anything'), ('rejecting party', 'anything'),
     "A party's negative stance toward a claim.", 'rejected_by'),
    ('offering as', 'binary relation between individual things',
     ['is offered as', 'is presented as', 'is intended as'], ['is the mode of'],
     [], None, None,
     'The status a claim is given: literal, figurative, analogy.', 'offered_as'),
    ('qualification', 'binary relation between individual things',
     ['is qualified as', 'is characterized as', 'is characterised as'], ['qualifies'],
     [], None, None,
     'Salience or ranking attached to a claim.', 'qualified_as'),
    ('commitment level', 'binary relation between individual things',
     ['has commitment', 'has as commitment'], ['is the commitment of'],
     [], None, None,
     'Certain / probable / possible / contested.', 'has_commitment'),
    ('exemplification', 'binary relation between kinds',
     ['is an example of', 'is an instance of the kind'], ['has as example', 'has example'],
     [], None, None,
     'A case illustrating a kind, without formal classification.', 'example_of'),
    ('dating', 'binary relation between individual things',
     ['is dated', 'is dated to', 'was published in the year'], ['is the date of'],
     [], None, None,
     "A document's date.", None),
    ('publication in a venue', 'binary relation between individual things',
     ['is published in', 'appears in', 'is reported in'], ['publishes', 'contains the publication'],
     [], None, None,
     'A document appears in a venue.', None),
    ('citation', 'binary relation between individual things',
     ['cites', 'refers to'], ['is cited by', 'is referred to by'],
     [], None, None,
     'A document references another.', None),
]

ROLE_OVERRIDES = {'citation': (('citing document', 'anything'), ('cited document', 'anything')),
 'conceptualization': (('conceptualized phenomenon', 'anything'), ('concept of it', 'anything')),
 'dating': (('dated document', 'anything'), ('date', 'anything')),
 'evidential support': (('evidence', 'anything'), ('supported claim', 'anything')),
 'exemplification': (('example', 'anything'), ('exemplified kind', 'anything')),
 'experiential projection': (('experienced structure', 'anything'), ('experience', 'anything')),
 'functional role possession': (('bearer', 'anything'), ('functional role', 'anything')),
 'objection': (('objecting claim', 'anything'), ('objected claim', 'anything')),
 'prediction relation': (('predicting theory', 'anything'), ('predicted observation', 'anything')),
 'publication in a venue': (('published document', 'anything'), ('venue', 'anything')),
 'reconstruction': (('reconstructing receiver', 'anything'), ('reconstructed state', 'anything')),
 'steering of attention': (('steering signal', 'anything'), ('steered process', 'anything')),
 'supervenience': (('supervening', 'anything'), ('supervenience base', 'anything'))}

DISJOINT_RELATIONS = [('projection of a state into a code', 'identity'),
 ('approximation of a process', 'identity'),
 ('metaphorical expression', 'identity'),
 ('metaphorical expression', '1225'),
 ('metaphorical expression', '1146'),
 ('structural analogy', 'identity'),
 ('functional analogy', 'identity'),
 ('supervenience', '1922'),
 ('constitution', '1922'),
 ('reduction', '1922'),
 ('realization of a function in a substrate', '1922'),
 ('identity', 'distinctness'),
 ('identity', '1146'),
 ('reduction', 'distinctness'),
 ('necessary condition', '1922'),
 ('sufficient condition', '1922'),
 ('endorsement', 'rejection'),
 ('objection', 'endorsement')]

# (name, kind, aliases, positions/questions they hold or posed)
PEOPLE = [
    ('Thomas Nagel', 'philosopher', ['Nagel', 'Nagel, T.', 'T. Nagel', 'Nagel 1974'], ['bat question']),
    ('Daniel Dennett', 'philosopher', ['Dennett', 'Dennett, D. C.', 'Dennett 1991'], ['illusionism', 'multiple drafts model']),
    ('David Chalmers', 'philosopher', ['Chalmers', 'Chalmers, D. J.', 'Chalmers 1995'], ['hard problem of consciousness', 'zombie argument']),
    ('Keith Frankish', 'philosopher', ['Frankish', 'Frankish, K.', 'Frankish 2016'], ['illusionism']),
    ('Joseph Levine', 'philosopher', ['Levine'], ['explanatory gap']),
    ('John Searle', 'philosopher', ['Searle'], ['Chinese room']),
    ('Ned Block', 'philosopher', ['Block'], ['access consciousness', 'phenomenal consciousness']),
    ('Frank Jackson', 'philosopher', ['F. Jackson'], ['knowledge argument']),
    ('Immanuel Kant', 'philosopher', ['Kant'], []),
    ('Antonio Damasio', 'neuroscientist', ['Damasio', 'Damasio, A. R.', 'Damasio 1994'], ['somatic marker hypothesis']),
    ('Pyotr Anokhin', 'physiologist', ['Anokhin', 'Anokhin, P. K.', 'Anokhin TFS 1974'], ['theory of functional systems']),
    ('Jürgen Schmidhuber', 'computer scientist', ['Schmidhuber', 'Schmidhuber, J.', 'Schmidhuber 2010'], ['artificial curiosity']),
    ('Ray Solomonoff', 'computer scientist', ['Solomonoff', 'Solomonoff, R. J.', 'Solomonoff 1964'], []),
    ('Marcus Hutter', 'computer scientist', ['Hutter', 'Hutter 2005'], []),
    ('Stephen Wolfram', 'computer scientist', ['Wolfram', 'Wolfram 2020'], ['computational irreducibility']),
    ('Charles Forgy', 'computer scientist', ['Forgy', 'Forgy, C. L.', 'Forgy 1982'], ['Rete algorithm']),
    ('Daniel Kahneman', 'psychologist', ['Kahneman', 'Kahneman, D.', 'Kahneman (2011)', 'Kahneman 2011'], ['dual-process theory']),
    ('Bernard Baars', 'psychologist', ['Baars', 'Baars, B. J.'], ['global workspace theory']),
    ('Giulio Tononi', 'neuroscientist', ['Tononi', 'Tononi and Koch 2015'], ['integrated information theory']),
    ('Francisco Varela', 'neuroscientist', ['Varela'], ['enactivism']),
    ('Evan Thompson', 'philosopher', ['Thompson'], ['enactivism']),
    ('Eleanor Rosch', 'psychologist', ['Rosch', 'Rosch, E.'], ['enactivism']),
    ('Joshua Conrad Jackson', 'psychologist', ['Jackson, J. C.', 'Jackson et al. 2019', 'Jackson et al. (2019)'], []),
    ('Benjamin Libet', 'neuroscientist', ['Libet', 'Libet et al. 1983'], []),
    ('Richard Nisbett', 'psychologist', ['Nisbett', 'Nisbett and Wilson 1977'], []),
    ('Michael Gazzaniga', 'neuroscientist', ['Gazzaniga', 'Gazzaniga 1998'], []),
    ('Evgeny Sokolov', 'physiologist', ['Sokolov', 'Sokolov 1963'], []),
    ('George Loewenstein', 'psychologist', ['Loewenstein', 'Frederick and Loewenstein 1999'], []),
    ('Victor Smirnov', 'philosopher', ['Smirnov', 'Smirnov, V.', 'Smirnov 2024'], []),
]

GELLISH_ALIASES = [('6233', 'entails', 'base'),
 ('6233', 'logically implies', 'base'),
 ('6233', 'is entailed by', 'inv'),
 ('6233', 'follows from', 'inv'),
 ('1922', 'is a cause of', 'base'),
 ('1922', 'causes', 'base'),
 ('1922', 'brings about', 'base'),
 ('1922', 'results from', 'inv'),
 ('1922', 'is a result of', 'inv'),
 ('1922', 'is an effect of', 'inv'),
 ('5126', 'is authored by', 'inv'),
 ('5126', 'is written by', 'inv'),
 ('4682', 'describes', 'base'),
 ('4682', 'characterizes', 'base'),
 ('1260', 'includes', 'inv'),
 ('1260', 'contains', 'inv'),
 ('1727', 'has', 'base'),
 ('1727', 'possesses', 'base'),
 ('5751', 'publishes', 'base')]
EXPLANATORY = ['projection of a state into a code', 'approximation of a process', 'conceptualization', 'experiential projection',
               'manifestation', 'encoding', 'realization of a function in a substrate', 'supervenience', 'constitution', 'reduction',
               'identity', 'explanation', 'generation', 'functional equivalence', 'metaphorical expression', 'reformulation']
# the psychophysical problem as a whole with its components (phrase, base direction)
PROBLEM_STRUCTURE = [
    (c, 'is a part of', 'psychophysical problem') for c in
    ('phenomenal experience', 'quale', 'hard problem of consciousness', 'explanatory gap', 'unity of consciousness', 'temporal unity of the self',
     'free will', 'mental causation', 'other minds', 'the self')
]
GELLISH_SEM = [('6233', 'implies'), ('1922', 'cause_of'), ('5828', 'identical_to'), ('5831', 'not_equal_to')]


def build(here, deps=None):
    e = Ext("philosophy_of_mind", *COLL, BASE, reference="standard references of the field")
    e.concepts(CONCEPTS)
    e.relations(RELATIONS, ROLE_OVERRIDES)
    e.people(PEOPLE, "assertion by a party")
    e.gellish_aliases(GELLISH_ALIASES)
    e.gellish_sem(GELLISH_SEM)
    e.disjoint_pairs(DISJOINT_RELATIONS)
    # relation types that count as *explaining* a phenomenon by a mechanism (used by the thesis stratum)
    for n in EXPLANATORY:
        e.sem.append((e.ref(n), 'explanatory'))
    e.sem.append(('1922', 'explanatory'))
    e.facts(PROBLEM_STRUCTURE)
    n = e.write(here)
    print(f"philosophy_of_mind: {len(CONCEPTS)} concepts, {len(RELATIONS)} relation types, {len(e.role_uid)} role kinds, {len(PEOPLE)} people, {n} rows")
    return e
